services:
  microservice:
    build: .
    image: microservice:latest
    container_name: microservice
    ports:
      - "8080:8080"
    volumes:
      - ./config/config.yaml:/cmd/config.yaml:ro
    command: ["--config", "/cmd/config.yaml"]
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://127.0.0.1:8080/health || exit 1"]
      interval: 10s
      timeout: 2s
      retries: 3
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    security_opt:
      - no-new-privileges:true
    read_only: true
    tmpfs:
      - /tmp
      - /run
    ulimits:
      nofile:
        soft: 262144
        hard: 262144